add fault logic
skrzepto/IPRO-VAULT-SERVER pull request #5
Opened 2016-10-08 21:54 UTC by sdimitro

2016-10-09 17:54 UTC, skrzepto requested changes
One small change in the delete_fault function and the rest looks good

2016-10-09 17:54 UTC, skrzepto commented on handlers/handlers.go
> +	Temperature   float64   `json:"temperature"`
Good catch :)

2016-10-09 17:54 UTC, skrzepto commented on handlers/handlers.go
> +func (i *Impl) GET_SensorData(rw http.ResponseWriter, req *http.Request, _ httprouter.Params) {
Thanks for cleaning this function up

2016-10-09 17:54 UTC, skrzepto commented on handlers/handlers.go
> +	js, err := json.Marshal(flts)
Should we nil the location instead? `i.faults[sensor_id] = nil` ? since this is delete the fault from the table

2016-10-09 18:35 UTC, skrzepto commented on handlers/handlers.go
> +	js, err := json.Marshal(flts)
Nvm i think its `delete(m, k)` where m is the map k is the key

2016-10-09 18:38 UTC, skrzepto commented on handlers/handlers.go
> +	js, err := json.Marshal(flts)
yup its delete

```
diff --git a/handlers/handlers.go b/handlers/handlers.go
index cda1ca6..4e70653 100644
--- a/handlers/handlers.go
+++ b/handlers/handlers.go
@@ -153,7 +153,8 @@ func (i *Impl) DELETE_Faults_ID(rw http.ResponseWriter, req *http.Request, ps ht
                return
        }
        js, err := json.Marshal(flts)
-       i.mu.Unlock()
+       delete(i.faults, sensor_id)
+       i.mu.Unlock()
 
        if err != nil {
                http.Error(rw, err.Error(), http.StatusInternalServerError)
```

2016-10-10 01:44 UTC, sdimitro commented on handlers/handlers.go
> +	js, err := json.Marshal(flts)
Sorry I was absent minded. I just gave gave back the faults for the specific sensor. I will change it now. Thanks for catching that

2016-10-10 01:49 UTC, sdimitro commented
Updated give it a look and feel free to merge

2016-10-10 15:41 UTC, skrzepto approved these changes

2016-10-10 15:42 UTC, merged